# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/252/bin/cmake

# The command to remove a file.
RM = /snap/cmake/252/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/human/Desktop/CA/TME/RenduMU/UM1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/human/Desktop/CA/TME/RenduMU/UM1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/252/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/252/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/human/Desktop/CA/TME/RenduMU/UM1/CMakeFiles /home/human/Desktop/CA/TME/RenduMU/UM1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/human/Desktop/CA/TME/RenduMU/UM1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named UM1

# Build rule for target.
UM1: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 UM1
.PHONY : UM1

# fast build rule for target.
UM1/fast:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/build
.PHONY : UM1/fast

Machine.o: Machine.cpp.o

.PHONY : Machine.o

# target to build an object file
Machine.cpp.o:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/Machine.cpp.o
.PHONY : Machine.cpp.o

Machine.i: Machine.cpp.i

.PHONY : Machine.i

# target to preprocess a source file
Machine.cpp.i:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/Machine.cpp.i
.PHONY : Machine.cpp.i

Machine.s: Machine.cpp.s

.PHONY : Machine.s

# target to generate assembly for a file
Machine.cpp.s:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/Machine.cpp.s
.PHONY : Machine.cpp.s

Machine2.o: Machine2.cpp.o

.PHONY : Machine2.o

# target to build an object file
Machine2.cpp.o:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/Machine2.cpp.o
.PHONY : Machine2.cpp.o

Machine2.i: Machine2.cpp.i

.PHONY : Machine2.i

# target to preprocess a source file
Machine2.cpp.i:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/Machine2.cpp.i
.PHONY : Machine2.cpp.i

Machine2.s: Machine2.cpp.s

.PHONY : Machine2.s

# target to generate assembly for a file
Machine2.cpp.s:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/Machine2.cpp.s
.PHONY : Machine2.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/UM1.dir/build.make CMakeFiles/UM1.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... UM1"
	@echo "... edit_cache"
	@echo "... Machine.o"
	@echo "... Machine.i"
	@echo "... Machine.s"
	@echo "... Machine2.o"
	@echo "... Machine2.i"
	@echo "... Machine2.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

